package com.shinestudio.app.airway.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table airlines.
 */
public class Airline {

    private Long id;
    private String name;
    private String iata;
    private String icao;
    private String callsign;
    private String country;

    public Airline() {
    }

    public Airline(Long id) {
        this.id = id;
    }

    public Airline(Long id, String name, String iata, String icao, String callsign, String country) {
        this.id = id;
        this.name = name;
        this.iata = iata;
        this.icao = icao;
        this.callsign = callsign;
        this.country = country;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIata() {
        return iata;
    }

    public void setIata(String iata) {
        this.iata = iata;
    }

    public String getIcao() {
        return icao;
    }

    public void setIcao(String icao) {
        this.icao = icao;
    }

    public String getCallsign() {
        return callsign;
    }

    public void setCallsign(String callsign) {
        this.callsign = callsign;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

}
