package com.shinestudio.app.airway.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table airports.
 */
public class Airport {

    private Long id;
    private String geohash;
    private String icao;
    private String iata;
    private String name;
    private String city;
    private String country;
    private Integer timezone;
    private Double latitude;
    private Double longitude;
    private Integer elevation;
    private Integer tran_alt;
    private Integer tran_level;
    private Integer longest_runway_length;

    public Airport() {
    }

    public Airport(Long id) {
        this.id = id;
    }

    public Airport(Long id, String geohash, String icao, String iata, String name, String city, String country, Integer timezone, Double latitude, Double longitude, Integer elevation, Integer tran_alt, Integer tran_level, Integer longest_runway_length) {
        this.id = id;
        this.geohash = geohash;
        this.icao = icao;
        this.iata = iata;
        this.name = name;
        this.city = city;
        this.country = country;
        this.timezone = timezone;
        this.latitude = latitude;
        this.longitude = longitude;
        this.elevation = elevation;
        this.tran_alt = tran_alt;
        this.tran_level = tran_level;
        this.longest_runway_length = longest_runway_length;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGeohash() {
        return geohash;
    }

    public void setGeohash(String geohash) {
        this.geohash = geohash;
    }

    public String getIcao() {
        return icao;
    }

    public void setIcao(String icao) {
        this.icao = icao;
    }

    public String getIata() {
        return iata;
    }

    public void setIata(String iata) {
        this.iata = iata;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Integer getTimezone() {
        return timezone;
    }

    public void setTimezone(Integer timezone) {
        this.timezone = timezone;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Integer getElevation() {
        return elevation;
    }

    public void setElevation(Integer elevation) {
        this.elevation = elevation;
    }

    public Integer getTran_alt() {
        return tran_alt;
    }

    public void setTran_alt(Integer tran_alt) {
        this.tran_alt = tran_alt;
    }

    public Integer getTran_level() {
        return tran_level;
    }

    public void setTran_level(Integer tran_level) {
        this.tran_level = tran_level;
    }

    public Integer getLongest_runway_length() {
        return longest_runway_length;
    }

    public void setLongest_runway_length(Integer longest_runway_length) {
        this.longest_runway_length = longest_runway_length;
    }

}
