package com.shinestudio.app.airway.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table countrys.
 */
public class Country {

    private String country;
    private Integer airports;

    public Country() {
    }

    public Country(String country, Integer airports) {
        this.country = country;
        this.airports = airports;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Integer getAirports() {
        return airports;
    }

    public void setAirports(Integer airports) {
        this.airports = airports;
    }

}
