package com.shinestudio.app.airway.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table navaids.
 */
public class Navaid {

    private Long id;
    private String geohash;
    private String identifier;
    private String name;
    private Double frequency;
    private Boolean vor;
    private Boolean dme;
    private Integer range;
    private Double latitude;
    private Double longitude;
    private Integer elevation;
    private String country_code;

    public Navaid() {
    }

    public Navaid(Long id) {
        this.id = id;
    }

    public Navaid(Long id, String geohash, String identifier, String name, Double frequency, Boolean vor, Boolean dme, Integer range, Double latitude, Double longitude, Integer elevation, String country_code) {
        this.id = id;
        this.geohash = geohash;
        this.identifier = identifier;
        this.name = name;
        this.frequency = frequency;
        this.vor = vor;
        this.dme = dme;
        this.range = range;
        this.latitude = latitude;
        this.longitude = longitude;
        this.elevation = elevation;
        this.country_code = country_code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGeohash() {
        return geohash;
    }

    public void setGeohash(String geohash) {
        this.geohash = geohash;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getFrequency() {
        return frequency;
    }

    public void setFrequency(Double frequency) {
        this.frequency = frequency;
    }

    public Boolean getVor() {
        return vor;
    }

    public void setVor(Boolean vor) {
        this.vor = vor;
    }

    public Boolean getDme() {
        return dme;
    }

    public void setDme(Boolean dme) {
        this.dme = dme;
    }

    public Integer getRange() {
        return range;
    }

    public void setRange(Integer range) {
        this.range = range;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Integer getElevation() {
        return elevation;
    }

    public void setElevation(Integer elevation) {
        this.elevation = elevation;
    }

    public String getCountry_code() {
        return country_code;
    }

    public void setCountry_code(String country_code) {
        this.country_code = country_code;
    }

}
