package com.shinestudio.app.airway.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table routes.
 */
public class Route {

    private Integer airline_id;
    private String source_code;
    private String destination_code;
    private Integer stops;
    private String equipment;

    public Route() {
    }

    public Route(Integer airline_id, String source_code, String destination_code, Integer stops, String equipment) {
        this.airline_id = airline_id;
        this.source_code = source_code;
        this.destination_code = destination_code;
        this.stops = stops;
        this.equipment = equipment;
    }

    public Integer getAirline_id() {
        return airline_id;
    }

    public void setAirline_id(Integer airline_id) {
        this.airline_id = airline_id;
    }

    public String getSource_code() {
        return source_code;
    }

    public void setSource_code(String source_code) {
        this.source_code = source_code;
    }

    public String getDestination_code() {
        return destination_code;
    }

    public void setDestination_code(String destination_code) {
        this.destination_code = destination_code;
    }

    public Integer getStops() {
        return stops;
    }

    public void setStops(Integer stops) {
        this.stops = stops;
    }

    public String getEquipment() {
        return equipment;
    }

    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }

}
