package com.shinestudio.app.airway.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table runways.
 */
public class Runway {

    private Integer airport_id;
    private String geohash;
    private String name;
    private Integer heading;
    private Integer length;
    private Integer width;
    private Integer ils;
    private Double ils_frequency;
    private Integer ils_heading;
    private Double latitude;
    private Double longitude;
    private Integer elevation;
    private Double glideslope_angle;
    private Double overflying_height;
    private Integer surface_type;
    private Integer status;

    public Runway() {
    }

    public Runway(Integer airport_id, String geohash, String name, Integer heading, Integer length, Integer width, Integer ils, Double ils_frequency, Integer ils_heading, Double latitude, Double longitude, Integer elevation, Double glideslope_angle, Double overflying_height, Integer surface_type, Integer status) {
        this.airport_id = airport_id;
        this.geohash = geohash;
        this.name = name;
        this.heading = heading;
        this.length = length;
        this.width = width;
        this.ils = ils;
        this.ils_frequency = ils_frequency;
        this.ils_heading = ils_heading;
        this.latitude = latitude;
        this.longitude = longitude;
        this.elevation = elevation;
        this.glideslope_angle = glideslope_angle;
        this.overflying_height = overflying_height;
        this.surface_type = surface_type;
        this.status = status;
    }

    public Integer getAirport_id() {
        return airport_id;
    }

    public void setAirport_id(Integer airport_id) {
        this.airport_id = airport_id;
    }

    public String getGeohash() {
        return geohash;
    }

    public void setGeohash(String geohash) {
        this.geohash = geohash;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getHeading() {
        return heading;
    }

    public void setHeading(Integer heading) {
        this.heading = heading;
    }

    public Integer getLength() {
        return length;
    }

    public void setLength(Integer length) {
        this.length = length;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getIls() {
        return ils;
    }

    public void setIls(Integer ils) {
        this.ils = ils;
    }

    public Double getIls_frequency() {
        return ils_frequency;
    }

    public void setIls_frequency(Double ils_frequency) {
        this.ils_frequency = ils_frequency;
    }

    public Integer getIls_heading() {
        return ils_heading;
    }

    public void setIls_heading(Integer ils_heading) {
        this.ils_heading = ils_heading;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Integer getElevation() {
        return elevation;
    }

    public void setElevation(Integer elevation) {
        this.elevation = elevation;
    }

    public Double getGlideslope_angle() {
        return glideslope_angle;
    }

    public void setGlideslope_angle(Double glideslope_angle) {
        this.glideslope_angle = glideslope_angle;
    }

    public Double getOverflying_height() {
        return overflying_height;
    }

    public void setOverflying_height(Double overflying_height) {
        this.overflying_height = overflying_height;
    }

    public Integer getSurface_type() {
        return surface_type;
    }

    public void setSurface_type(Integer surface_type) {
        this.surface_type = surface_type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
